In [1]:
import numpy as np

In [4]:
numbers = np.linspace(5, 50, 24, dtype=int).reshape(4, -1)

In [5]:
numbers

array([[ 5,  6,  8, 10, 12, 14],
       [16, 18, 20, 22, 24, 26],
       [28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50]])

In [6]:
mask = numbers % 4 == 0

In [7]:
mask

array([[False, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False]])

In [8]:
numbers[mask]

array([ 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48])

In [3]:
numbers = np.linspace(5, 50, 24, dtype=int).reshape(4, -1)

In [5]:
by_four = numbers[numbers % 4 == 0]

In [6]:
by_four

array([ 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48])

In [7]:
from numpy.random import default_rng

In [8]:
rng = default_rng()

In [9]:
values = rng.standard_normal(10000)

In [10]:
values[:5]

array([-0.01897277,  1.6705013 , -1.10829512,  0.11827586,  0.3528664 ])

In [11]:
std = values.std()

In [12]:
std

0.9999780613673344

In [13]:
filtered = values[(values > -2 * std) & (values < 2 * std)]

In [14]:
filtered.size

9549

In [15]:
values.size

10000

In [16]:
filtered.size / values.size

0.9549